### ISSUE TITLE
Problems when I make all

### ISSUE THREAD

**Issue by VeryGenome** [pawamoy/docker-nginx-auth-request-django-shiny-example#1]
Excuse me,I git clone it ,and I have installed the Docker and Docker-Compose also,but when I make all ,some errors occurred,could you help me to solve it?Thank you!
$ make all
Creating network "docker-django-shiny_default" with the default driver
ERROR: 404 page not found
make: *** [dev-yarn] Error 1

**Comment by pawamoy** [comment]
Hi! I just tried it and it works fine! Can you try again? Maybe it was a temporary network failure :confused: 

Also, I'm getting another error in `build`:
```
The following packages have unmet dependencies:
 r-base : Depends: r-recommended (= 3.5.0.20180627-1trusty) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Will try to fix that asap.

**Comment by VeryGenome** [comment]
Thank you!But I think it's not caused by temporary network failure as I tried so many times.I have install all the dependency and run the shiny,it's OK,but when I run the djangoapp ,another error occurred:
$python3 djangoapp/manage.py runserver localhost:8000

django.db.utils.OperationalError: could not translate host name "database" to address: Name or service not known

**Comment by pawamoy** [comment]
You're not supposed to use Django's `runserver` command. Specifically, if you only start the `djangoapp` container, then the database container is not accessible, hence the `OperationalError you're getting`.

Did you copy the full output? I have no way to tell why you get a `ERROR: 404 page not found` in the `dev-yarn` step :confused:

If you have Yarn installed on your machine, could try to directly go into `djangoapp/static` and run `yarn`, to see what happens and if you get the same error?

**Comment by VeryGenome** [comment]
Here is the error:
$cd djangoapp/static
$yarn
/usr/share/yarn/lib/cli.js:45699
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Thank you!

**Comment by pawamoy** [comment]
Well, this is another issue :laughing: It seems your version of Yarn is not compatible with your version of Node.js. This incompatibility should not occur while using the Dockerfiles/containers.

**Comment by VeryGenome** [comment]
Thank you so much!So many issues occurred maybe because my system is Centos 6.3,this server I have used more than 6 years and it's now out of date,and the Docker version is 1.7.1,maybe I should change another server to solve this.Thanks!

**Comment by pawamoy** [comment]
You are welcome!

If you can try it on another OS or on a more recent version of Docker (I'm on version 18.09.5!!), to see if it works, it could help resolve this indeed :slightly_smiling_face:
