### ISSUE TITLE
Unable to Make All

### ISSUE THREAD

**Issue by IlanReinstein** [pawamoy/docker-nginx-auth-request-django-shiny-example#24]
Hi, 
I have cloned the repo and tried building the whole package without any luck. 
I attach a picture of the error message. I tried troubleshooting some of these but nothing changed.
I am using GNU Make 3.81, Docker version 20.10.22, build 3a2c30b, Docker Compose version v2.15.1 On a Mac, macOS 12.5.1 Intel.
Let me know if you need anything else from me, I'll be happy to keep the conversation open.

`Reading package lists...
W: GPG error: https://deb.nodesource.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280

Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python
  python-minimal python2.7 python2.7-minimal
Suggested packages:
  python-doc python-tk python2.7-doc binutils binfmt-support
The following NEW packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib nodejs python
  python-minimal python2.7 python2.7-minimal
0 upgraded, 8 newly installed, 0 to remove and 1 not upgraded.
Need to get 17.8 MB of archives.
After this operation, 86.5 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  nodejs
E: There are problems and -y was used without --force-yes
/bin/sh: 1: npm: not found
/bin/sh: 1: npm: not found
1 error occurred:
	* Status: The command '/bin/sh -c apt-get update;     apt-get install -y curl;     curl -sL https://deb.nodesource.com/setup_8.x | bash -;     apt-get install -y nodejs;     npm update -g npm;     npm install -g yarn;' returned a non-zero code: 127, Code: 127`

**Comment by pawamoy** [comment]
Hi, thanks for the report!

This repository is getting old, that doesn't surprise me that things are broken :sweat_smile: 
I'd simply recommend using more recent versions of everything, in Dockerfiles and docker-compose YAML files, checking out how to install these more recent versions on their official docs.

A PR updating everything would be quite welcome!

**Comment by IlanReinstein** [comment]
Yeah, makes sense. If I figure out a workaround, I'll definitely share a PR.
Thanks, will close
