### ISSUE TITLE
proxy_redirect do not execute in the nginx configure

### ISSUE THREAD

**Issue by wulj5** [pawamoy/docker-nginx-auth-request-django-shiny-example#34]
Why [proxy_redirect command](https://github.com/pawamoy/docker-nginx-auth-request-django-shiny-example/blob/master/config/nginx/conf.d/local.conf#L47) do not work in the [nginx configure file](https://github.com/pawamoy/docker-nginx-auth-request-django-shiny-example/blob/master/config/nginx/conf.d/local.conf),
I hope it will redirect all the content from shinyapp server to some front-end URI, however, this line do not execute at all, would you please help me ?

**Comment by pawamoy** [comment]
Sorry, it's been too long since I used Nginx, you'll have better luck on StackOverflow or with LLMs ☺️
